# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedfast < Formula
  desc "AI-powered PostgreSQL database seeding tool"
  homepage "https://seedfa.st"
  version "2.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.seedfa.st/seedfast/v2.4.1/seedfast_Darwin_x86_64.tar.gz"
      sha256 "838396a3bdd7dbdf940db8a54171d1fcba07a1a43f1e76bb77db9a7185ac8c9e"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.seedfa.st/seedfast/v2.4.1/seedfast_Darwin_arm64.tar.gz"
      sha256 "fd3bb098347a55c9937f88540fc02cfbd0c17ff5f1a092bde43ffb8890ace318"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.4.1/seedfast_Linux_x86_64.tar.gz"
      sha256 "ca0471deb47e99623821d3f7948ee98b161983789e3534f0ea750f73615b1237"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.4.1/seedfast_Linux_arm64.tar.gz"
      sha256 "bb1baffe28d2821ffccafe0612441f5bd2b2a3cb62a109ecd8d2baa4c8e64d4b"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  def caveats
    <<~EOS
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.
    EOS
  end

  test do
    system "#{bin}/seedfast", "version"
  end
end
