# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedfast < Formula
  desc "AI-powered PostgreSQL database seeding tool"
  homepage "https://seedfa.st"
  version "2.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.2.2/seedfast_Darwin_x86_64.tar.gz"
      sha256 "0b4dceec088759633718f9d8b4b45dd9a578dc0ba01c88c2cdd788bccada2f0b"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.2.2/seedfast_Darwin_arm64.tar.gz"
      sha256 "700c3a92e1cb41754adfc12691de13cb91ed16d4106e5497e8476ea267cea2d3"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.2.2/seedfast_Linux_x86_64.tar.gz"
      sha256 "e6b7b244fe9da899117bfb2a062200baf678d7be1648b17d4eb6448b56e70a60"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.2.2/seedfast_Linux_arm64.tar.gz"
      sha256 "ee10b02508fa019b879d7869e8822436c5322bc3f1e7fb32b4b980d08d4194d7"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  def caveats
    <<~EOS
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.
    EOS
  end

  test do
    system "#{bin}/seedfast", "version"
  end
end
