# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedfast < Formula
  desc "AI-powered PostgreSQL database seeding tool"
  homepage "https://seedfa.st"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.3.0/seedfast_Darwin_x86_64.tar.gz"
      sha256 "865754f2cec434236de08431ad115d2dffc6392db6d2bf15f16492e3099f42a2"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.3.0/seedfast_Darwin_arm64.tar.gz"
      sha256 "c103683073e245dfd4ebd0b9f619fad982ce574c96859145f132e378aa5bb5f7"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.3.0/seedfast_Linux_x86_64.tar.gz"
      sha256 "4a12ad85f17e084566a6005fe1d0b239035301b0a190feb222849c1ccebaf6ab"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/argon-it/seedfast-cli/releases/download/v2.3.0/seedfast_Linux_arm64.tar.gz"
      sha256 "15edcfc6bb34a43565d4b382bbbcf25bb6fc0ec7c48b9ccbeb253aae0afbdfb0"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  def caveats
    <<~EOS
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.
    EOS
  end

  test do
    system "#{bin}/seedfast", "version"
  end
end
